### ISSUE TITLE
release hex file

### ISSUE THREAD

**Issue by puffatron** [dornbirndevelops/nintendo-switch-controller-arduino#1]
First off, thank you a ton for this!
Everything works great except when i flash the releasebox.hex , my arduino r3 is not 
recognized as any usb device or a switch controller.
Thanks again!
`

**Comment by dornbirndevelops** [comment]
hello, i appreciate your excitement for this little project.
i'll investigate into that problem.
did you try other hex files?

**Comment by dornbirndevelops** [comment]
I've digged a bit deeper into the issue and found out that there are too many input steps.
It seems the microcontroller has reached its memory limits using this architecture -> meaning the whole thing will have to be rewritten. I'll do it when I get to it.

**Comment by titicruz** [comment]
you can now release massive in pokemon home. maybe this is not needed anymore.

**Comment by dornbirndevelops** [comment]
this issue could also be resolved by storing the input commands within flash memory.
