### ISSUE TITLE
INPUTS scripts should be stored in flash, not RAM.

### ISSUE THREAD

**Issue by WestfW** [dornbirndevelops/nintendo-switch-controller-arduino#2]
the INPUTS[] "script" should be allocated in flash, rather than in RAM.  This would allow even the releasebox script to fit comfortably with no memory issues.

The easiest way to do this, given a relatively recent avr-gcc, is simply to add the "__flash" "named memory space qualifier" to the declarations.
Diffs attached.

I can't test this (no switch!), but it should be straightforward, and it does compile.
The results are ("-" lines are old version.  "+" lines are new):
```
 avr-size --mcu=atmega16u2 --format=avr masterballs.elf
-Program:    3840 bytes (23.4% Full)
-Data:        358 bytes (69.9% Full)
+Program:    3838 bytes (23.4% Full)
+Data:         36 bytes (7.0% Full)

 avr-size --mcu=atmega16u2 --format=avr releasebox.elf
-Program:    4986 bytes (30.4% Full)
-Data:       1504 bytes (293.8% Full)
+Program:    4984 bytes (30.4% Full)
+Data:         36 bytes (7.0% Full)

 avr-size --mcu=atmega16u2 --format=avr spam-a.elf
-Program:    3750 bytes (22.9% Full)
-Data:        268 bytes (52.3% Full)
+Program:    3748 bytes (22.9% Full)
+Data:         36 bytes (7.0% Full)

 avr-size --mcu=atmega16u2 --format=avr wattsfarmer.elf
-Program:    3750 bytes (22.9% Full)
-Data:        268 bytes (52.3% Full)
+Program:    3748 bytes (22.9% Full)
+Data:         36 bytes (7.0% Full)

 avr-size --mcu=atmega16u2 --format=avr wildareabreeding.elf
-Program:    3696 bytes (22.6% Full)
-Data:        214 bytes (41.8% Full)
+Program:    3694 bytes (22.5% Full)
+Data:         36 bytes (7.0% Full)

 avr-size --mcu=atmega16u2 --format=avr dracovish.elf
-Program:    3630 bytes (22.2% Full)
-Data:        148 bytes (28.9% Full)
+Program:    3628 bytes (22.1% Full)
+Data:         36 bytes (7.0% Full)
```

[use_flash.diff.txt](https://github.com/dornbirndevelops/nintendo-switch-controller-arduino/files/4158547/use_flash.diff.txt)

**Comment by titicruz** [comment]
Hello,

do you know how the time works? like what does { NOTHING,  250 } means? 250 ms doing nothing?

**Comment by titicruz** [comment]
I did some tests and figured out that one of the scripts (whattsfarm) takes  aprox. 33 sec to run. I Added all the values (removing the first 11 ) and saw that if i multiply the result by 8 i get the value of 
32600(ms?).

**Comment by dornbirndevelops** [comment]
thank you @WestfW for introducing me the `__flash` keyword, this resolved the space limitation (for now).
