### ISSUE TITLE
Make running into errors

### ISSUE THREAD

**Issue by IronBit-0** [dornbirndevelops/nintendo-switch-controller-arduino#6]
This is the error I receive upon running "make" in the directory. I am running Windows 10.

      0 [main] sh 10552 sync_with_child: child 14796(0x1E4) died before initialization with status code 0xC0000142
    123 [main] sh 10552 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 13308 sync_with_child: child 17548(0x1F0) died before initialization with status code 0xC0000142
    100 [main] sh 13308 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 12092 sync_with_child: child 18344(0x1F0) died before initialization with status code 0xC0000142
     98 [main] sh 12092 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
 [INFO]    : Begin compilation of project "Joystick"...

avr-gcc (WinAVR 20100110) 4.3.3
Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file "Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega16u2 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/  -I. -IC:/Users/User8/Desktop/Switch-Fightstick-master/LUFA/LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL  -MMD -MP -MF obj/Joystick.d Joystick.c -o obj/Joystick.o
Joystick.c: In function 'SetupHardware':
Joystick.c:54: warning: implicit declaration of function 'clock_prescale_set'
Joystick.c:54: error: 'clock_div_1' undeclared (first use in this function)
Joystick.c:54: error: (Each undeclared identifier is reported only once
Joystick.c:54: error: for each function it appears in.)
make: *** [obj/Joystick.o] Error 1

**Comment by dornbirndevelops** [comment]
The error you're experiencing occurs when the compiler can not resolve a symbol before first usage.
`Joystick.c:54: warning: implicit declaration of function 'clock_prescale_set'` this means the function `clock_prescale_set` could not be found.

I've looked at your path where you stored the project.
`C:/Users/User8/Desktop/Switch-Fightstick-master`
I assume you used the download Zip button on the main page to download the source code.
Unfortunately this does not pack the required submodule (LUFA) with it (tested it just now).

Therefore please make sure you also have the content within the LUFA directory.
you can either download the submodule https://github.com/abcminiuser/lufa/tree/597fbf47cd2551423a231ac747e2f1405cf9306a as a zip file and paste it in the appropriate location.

Or the easier solution would be to install git https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/Git-2.26.2-64-bit.exe and run the command stated in the Readme from a commandline prompt.
`git clone --recursive git@github.com:dornbirndevelops/nintendo-switch-controller-arduino.git`
the recursive part also downloads linked submodules.

**Comment by dornbirndevelops** [comment]
i'll mark this as closed now, feel free to re-open the issue when the problem persists.
